### ISSUE TITLE
Todo / ideas

### ISSUE THREAD

**Issue by BuckarooBanzay** [luk3yx/minetest-doom_hud#1]
I'd like to add the following if that's ok for you:
* [ ] add an api for use in other mods
* [ ] add a proper readme (with screenshot:)
* [ ] add textures for the lower right part (yellow-ish text with various ammo-stats)
* [ ] add textures for the color cards elements
* [ ] Maybe: "bloody"/damaged sam texture (might be too gore, not sure :shrug:)

Other issues:
* [x] code license #2
* [x] public repo (is there a reason for making this private?)

btw: this was an awesome idea :+1:
